### ISSUE TITLE
HTTP/2 concurrent requests

### ISSUE THREAD

**Issue by markreg** [duojs/pack#37]
Is duo-pack useful in light of the concurrent request optimization in HTTP/2?

**Comment by dominicbarnes** [comment]
This isn't really a bug/issue, so I'll close this after my response. If any of the other @duojs/owners want to chime in, feel free to add to my thoughts here as well.

I've not used HTTP/2 in any way yet, so I'm probably going to say some incorrect things. But based on what I do know, I think I can provide a useful response.

`duo-pack` handles mapping `require` statements to all the dependencies in your app. (once they've been resolved and downloaded) As of now, simply running all those modules in parallel in your browser won't work out of the box, since the logic for `require()` will not have any way to communicate between all those parallel scripts. (especially when it comes to dependency order and stuff like that)

HTTP/2 does handle loading assets in parallel using a single connection, which does help the problem a lot, but I suspect it doesn't eliminate _all_ the overhead of multiple requests. Plus, by itself it does not address the issue of dependency ordering. In the land of "component" and "duo", which focus on _lots_ of small dependencies, this is much harder than using a few monoliths like jQuery and jQuery UI + plugins.

All that being said, HTTP/2 will not eliminate the need for duo-pack, but there will be other ways that duo can benefit from HTTP/2. (not to mention any other new technologies meant to aid web developers)

**Comment by stephenmathieson** [comment]
HTTP/2 would only make a noticeable difference at buil
